# Generated by Django 2.2.17 on 2020-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exercises',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
